=== ahpoder/masterofit2009/xml_and_Web/xmltek/seminar1/opg11/moviestudio.xsd
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        xmlns:m="http://moviesstudio.org"
        targetNamespace="http://moviesstudio.org">

	<element name="movie" type="m:MovieType"/>
	<element name="title" type="string"/>
	<element name="part" type="m:PartType"/>
	<element name="cut" type="m:CutType"/>
	<element name="film" type="m:FilmType"/>
	<element name="time" type="time"/>
	<element name="duration" type="duration"/>
	<attribute name="number" type="NCName"/>

	<complexType name="MovieType">
      <sequence>
        <element ref="m:title"/>
        <element ref="m:part" minOccurs="0" maxOccurs="unbounded"/>
      </sequence>
    </complexType>

	<complexType name="PartType">
      <sequence>
        <element ref="m:title"/>
        <choice>
			<element ref="m:part" minOccurs="1" maxOccurs="unbounded"/>
			<element ref="m:cut"/>
		</choice>
      </sequence>
    </complexType>
	
	<complexType name="CutType">
      <sequence>
        <element ref="m:film"/>
        <element ref="m:time"/>
        <element ref="m:duration"/>
      </sequence>
    </complexType>
	
	<complexType name="FilmType">
		<attribute name="number" type="NCName"/>
		<!--attribute ref="m:number"/-->
    </complexType>
</schema>

=== ahpoder/masterofit2009/xml_and_Web/xmltek/seminar1/opg11/moviestudio.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--DOCTYPE movie SYSTEM "moviestudio.dtd"-->
<!--movie-->
<movie xmlns="http://moviesstudio.org" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://moviesstudio.org moviestudio.xsd">
	<title>Example movie</title>
	<part>
		<title>Example part</title>
		<part>
			<title>inner example part</title>
			<cut>
				<film number="r1"/>
				<time>16:29:00</time>
				<duration>P0Y0M0DT1H30M</duration>
			</cut>
		</part>
	</part>
</movie>
